import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../storage/output_storage_service.dart';
import 'document_gen_service.dart';

/// Generates PDF documents from AI-generated content.
/// Runs on background isolate to prevent UI freezing.
class PdfGenerator {
  /// Generate a PDF from document content.
  static Future<String> generatePdf({
    required String title,
    required String content,
    required DocumentType type,
    Map<String, dynamic>? metadata,
  }) async {
    final pdf = pw.Document();

    // Sanitize content to remove emojis and unsupported Unicode characters
    final safeTitle = _sanitizeForPdf(title);
    final safeContent = _sanitizeForPdf(content);
    final safeMetadata = metadata?.map((key, value) => MapEntry(key, _sanitizeForPdf(value.toString())));

    // Parse content into sections
    final sections = _parseContent(safeContent, type);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(48),
        header: (context) => _buildHeader(safeTitle, type),
        footer: (context) => _buildFooter(),
        build: (context) => [
          _buildTitlePage(safeTitle, type, safeMetadata),
          pw.SizedBox(height: 20),
          ...sections,
        ],
      ),
    );

    final dir = await _getDocumentsDir();
    final filename = '${_sanitizeFilename(safeTitle)}.pdf';
    final file = File('${dir.path}/$filename');
    try {
      await file.writeAsBytes(await pdf.save());
    } catch (e) {
      // Fallback: write to a simpler path
      final fallbackDir = Directory('${dir.path}/../ambot_output/documents');
      if (!await fallbackDir.exists()) await fallbackDir.create(recursive: true);
      final fallback = File('${fallbackDir.path}/$filename');
      await fallback.writeAsBytes(await pdf.save());
      return fallback.path;
    }
    return file.path;
  }

  static pw.Widget _buildHeader(String title, DocumentType type) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 1),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            type.label.toUpperCase(),
            style: pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey600,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.Text(
            title.length > 40 ? '${title.substring(0, 40)}...' : title,
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildFooter() {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(color: PdfColors.grey300, width: 1),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.center,
        children: [
          pw.Text(
            'Generated by Ambot AI',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildTitlePage(String title, DocumentType type, Map<String, dynamic>? metadata) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Container(
          padding: const pw.EdgeInsets.all(24),
          decoration: pw.BoxDecoration(
            color: PdfColors.blue50,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                type.label.toUpperCase(),
                style: pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.blue700,
                  fontWeight: pw.FontWeight.bold,
                  letterSpacing: 2,
                ),
              ),
              pw.SizedBox(height: 12),
              pw.Text(
                title,
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue900,
                ),
              ),
              if (metadata != null && metadata['topic'] != null) ...[
                pw.SizedBox(height: 8),
                pw.Text(
                  'Topic: ${metadata['topic']}',
                  style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
                ),
              ],
              pw.SizedBox(height: 8),
              pw.Text(
                'Generated on ${DateTime.now().toString().split(' ')[0]}',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
              ),
            ],
          ),
        ),
        pw.SizedBox(height: 20),
      ],
    );
  }

  static List<pw.Widget> _parseContent(String content, DocumentType type) {
    final widgets = <pw.Widget>[];
    final lines = content.split('\n');
    String currentParagraph = '';

    for (final line in lines) {
      final trimmed = line.trim();

      if (trimmed.isEmpty) {
        if (currentParagraph.isNotEmpty) {
          widgets.add(_buildParagraph(currentParagraph));
          currentParagraph = '';
        }
        widgets.add(pw.SizedBox(height: 8));
        continue;
      }

      // Check for headings
      if (trimmed.startsWith('# ')) {
        if (currentParagraph.isNotEmpty) {
          widgets.add(_buildParagraph(currentParagraph));
          currentParagraph = '';
        }
        widgets.add(pw.SizedBox(height: 12));
        widgets.add(_buildHeading(trimmed.substring(2), level: 1));
        widgets.add(pw.SizedBox(height: 8));
      } else if (trimmed.startsWith('## ')) {
        if (currentParagraph.isNotEmpty) {
          widgets.add(_buildParagraph(currentParagraph));
          currentParagraph = '';
        }
        widgets.add(pw.SizedBox(height: 10));
        widgets.add(_buildHeading(trimmed.substring(3), level: 2));
        widgets.add(pw.SizedBox(height: 6));
      } else if (trimmed.startsWith('### ')) {
        if (currentParagraph.isNotEmpty) {
          widgets.add(_buildParagraph(currentParagraph));
          currentParagraph = '';
        }
        widgets.add(pw.SizedBox(height: 8));
        widgets.add(_buildHeading(trimmed.substring(4), level: 3));
        widgets.add(pw.SizedBox(height: 4));
      } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ') || trimmed.startsWith('• ')) {
        if (currentParagraph.isNotEmpty) {
          widgets.add(_buildParagraph(currentParagraph));
          currentParagraph = '';
        }
        widgets.add(_buildBullet(trimmed.substring(2)));
      } else if (RegExp(r'^\d+[\.\)]\s').hasMatch(trimmed)) {
        if (currentParagraph.isNotEmpty) {
          widgets.add(_buildParagraph(currentParagraph));
          currentParagraph = '';
        }
        final match = RegExp(r'^(\d+)[\.\)]\s+(.*)').firstMatch(trimmed);
        if (match != null) {
          widgets.add(_buildNumberedItem(match.group(1)!, match.group(2)!));
        }
      } else {
        currentParagraph += (currentParagraph.isEmpty ? '' : ' ') + trimmed;
      }
    }

    if (currentParagraph.isNotEmpty) {
      widgets.add(_buildParagraph(currentParagraph));
    }

    return widgets;
  }

  static pw.Widget _buildHeading(String text, {int level = 1}) {
    final fontSize = level == 1 ? 18.0 : (level == 2 ? 15.0 : 13.0);
    final fontWeight = level == 1 ? pw.FontWeight.bold : pw.FontWeight.normal;
    final color = level == 1 ? PdfColors.blue900 : PdfColors.blue800;

    return pw.Text(
      text,
      style: pw.TextStyle(
        fontSize: fontSize,
        fontWeight: fontWeight,
        color: color,
      ),
    );
  }

  static pw.Widget _buildParagraph(String text) {
    return pw.Text(
      text,
      style: const pw.TextStyle(
        fontSize: 11,
        color: PdfColors.grey900,
        lineSpacing: 4,
      ),
    );
  }

  static pw.Widget _buildBullet(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(left: 16, bottom: 4),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('• ', style: const pw.TextStyle(fontSize: 11, color: PdfColors.blue700)),
          pw.Expanded(
            child: pw.Text(
              text,
              style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey900),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildNumberedItem(String number, String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(left: 16, bottom: 4),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            width: 20,
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              '$number.',
              style: pw.TextStyle(fontSize: 11, color: PdfColors.blue700, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.SizedBox(width: 8),
          pw.Expanded(
            child: pw.Text(
              text,
              style: pw.TextStyle(fontSize: 11, color: PdfColors.grey900),
            ),
          ),
        ],
      ),
    );
  }

  static Future<Directory> _getDocumentsDir() async {
    try {
      return await OutputStorageService.instance.dir(OutputType.documents);
    } catch (_) {
      // Hard fallback
      final dir = Directory('${await _fallbackDir()}/ambot_output/documents');
      if (!await dir.exists()) await dir.create(recursive: true);
      return dir;
    }
  }

  static Future<String> _fallbackDir() async {
    try {
      return (await getApplicationDocumentsDirectory()).path;
    } catch (_) {
      // Platform-specific fallbacks
      if (Platform.isAndroid) {
        return '/storage/emulated/0/Android/data/com.ambot.ambot_ai/files';
      } else if (Platform.isWindows) {
        return '${Platform.environment['USERPROFILE']}\\Documents';
      } else if (Platform.isMacOS || Platform.isLinux) {
        return '${Platform.environment['HOME']}/Documents';
      }
      return Directory.current.path;
    }
  }

  static String _sanitizeFilename(String name) {
    return name
        .replaceAll(RegExp(r'[<>:"/\\|?*]'), '')
        .replaceAll(RegExp(r'\s+'), '_')
        .substring(0, name.length.clamp(0, 100));
  }

  /// Remove emojis and unsupported Unicode characters that cause PDF font errors.
  /// The default Helvetica font only supports Latin-1 characters.
  static String _sanitizeForPdf(String text) {
    return text.replaceAll(RegExp(
      r'[\u{1F600}-\u{1F64F}'  // Emoticons
      r'\u{1F300}-\u{1F5FF}'  // Misc Symbols and Pictographs
      r'\u{1F680}-\u{1F6FF}'  // Transport and Map
      r'\u{1F700}-\u{1F77F}'  // Alchemical Symbols
      r'\u{1F780}-\u{1F7FF}'  // Geometric Shapes Extended
      r'\u{1F800}-\u{1F8FF}'  // Supplemental Arrows-C
      r'\u{1F900}-\u{1F9FF}'  // Supplemental Symbols and Pictographs
      r'\u{1FA00}-\u{1FA6F}'  // Chess Symbols
      r'\u{1FA70}-\u{1FAFF}'  // Symbols and Pictographs Extended-A
      r'\u{2600}-\u{26FF}'    // Misc Symbols
      r'\u{2700}-\u{27BF}'    // Dingbats
      r'\u{FE00}-\u{FE0F}'    // Variation Selectors
      r'\u{1F000}-\u{1F02F}'  // Mahjong Tiles
      r'\u{1F0A0}-\u{1F0FF}'  // Playing Cards
      r'\u{200D}'             // Zero Width Joiner
      r'\u{20E3}'             // Combining Enclosing Keycap
      r'\u{FE0F}'             // Variation Selector-16
      r'\u{1F1E6}-\u{1F1FF}]' // Regional Indicator Symbols (Flags)
      , caseSensitive: false, unicode: true), '');
  }
}
